code --install-extension adamwalzer.scss-lint
code --install-extension adpyke.vscode-sql-formatter
code --install-extension alphabotsec.vscode-eclipse-keybindings
code --install-extension arzg.eclipse
code --install-extension bierner.emojisense
code --install-extension brunnerh.insert-unicode
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension cweijan.vscode-mysql-client2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcortes92.FreeMarker
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension exiasr.hadolint
code --install-extension firsttris.vscode-jest-runner
code --install-extension freebroccolo.reasonml
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-execution
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension IronGeek.vscode-env
code --install-extension janisdd.vscode-edit-csv
code --install-extension jhipster-ide.jdl
code --install-extension joaompinto.vscode-graphviz
code --install-extension jvalecillos.gpg
code --install-extension krueger71.crt-themes
code --install-extension mathiasfrohlich.Kotlin
code --install-extension me-dutour-mathieu.vscode-github-actions
code --install-extension mhutchie.git-graph
code --install-extension moshfeu.compare-folders
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.hexeditor
code --install-extension octref.vetur
code --install-extension Perkovec.emoji
code --install-extension rebornix.prolog
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension REditorSupport.r
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension silvenon.mdx
code --install-extension stardog-union.stardog-rdf-grammars
code --install-extension stardog-union.vscode-langserver-turtle
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-french
code --install-extension streetsidesoftware.code-spell-checker-french-reforme
code --install-extension tamasfe.even-better-toml
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zxh404.vscode-proto3
